baseURL = "https://jameskiefer.com/"
languageCode = "en-us"
title = "James Kiefer"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-124058172-1"

theme = "carbon"
timeout = 300000

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "James Kiefer"
  publisher = "James Kiefer"
  publisherLogo = "https://jameskiefer.com/logo.png"
  portrait = "img/portrait.jpg"
  description = "Release Engineer, Software Developer, Maker and Drone Pilot"
  seoDescription = "An American Release Engineer, Software Developer, Maker and Drone Pilot"
  tags = [
    "James Kiefer", "Software Developer", "Maker", "Drone Pilot", "Release Engineer",
    "DIY Ideas", "CNC Projects", "Laser Projects", "3D Printing", "Linux", "CAD", 
    "Electronics", "R/C"
  ]

[params.staticman]
  username = "zinefer"
  repository = "zinefer.github.com"
  gitprovider = "github"
  branch = "master"
  baseurl = "staticman-owl.herokuapp.com"
  notifications = false