baseURL = "https://jameskiefer.com/"
languageCode = "en-us"
title = "James Kiefer"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-124058172-1"

theme = "carbon"
timeout = 300000

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "James Kiefer"
  publisher = "James Kiefer"
  publisherLogo = "http://jameskiefer.com/logo.png"
  portrait = "img/portrait.jpg"
  description = "Release Engineer, Software Developer, Maker and Drone Pilot"

[params.staticman]
  username = "zinefer"
  repository = "zinefer.github.com"
  branch = "master"
  notifications = false
