baseURL = "//jameskiefer.com/"
languageCode = "en-us"
title = "James Kiefer"

canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-124058172-1"

theme = "carbon"

[params]
    portrait = "img/portrait.jpg"
    description = "Release Engineer, Software Developer, Maker and Drone Pilot"



[[params.social]]
    title = "Email"
    url = "mailto:john@doe.com"
[[params.social]]
    title = "Follow @johndoe"
    url = "https://twitter.com/johndoe"
[[params.social]]
    title = "Github"
    url = "https://github.com/johndoe"
[[params.social]]
    title = "Facebook"
    url = "https://facebook.com/johndoe"