baseURL = "http://jameskiefer.com/"
languageCode = "en-us"
title = "James Kiefer"

enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true
googleAnalytics = "UA-124058172-1"

theme = "carbon"

[params]
  author = "James Kiefer"
  publisher = "James Kiefer"
  publisherLogo = "http://jameskiefer.com/logo.png"
  portrait = "img/portrait.jpg"
  description = "Release Engineer, Software Developer, Maker and Drone Pilot"
