name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout resources cache
      uses: actions/checkout@v2
      with:
        ref: resources
        path: resources

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2

    - name: Install dependencies
      run: ./Taskfile.sh install

    - name: Build content
      run: ./Taskfile.sh build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

    - name: Commit resources cache
      uses: EndBug/add-and-commit@v4
      with:
        message: "Deploy #${{ github.run_number }}"
        cwd: resources
        ref: resources
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove .git directory
      run: rm -rf public/.git

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    # - name: Publish content
    #   run: ./Taskfile.sh deploy ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
