name: Publish Static Web App to Azure Blob Storage

on: 
  push:
    branches:
      - master

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout resources cache
      uses: actions/checkout@v2
      with:
        ref: resources
        path: resources

    - name: Install dependencies
      run: ./Taskfile.sh install
    
    - name: Build content
      run: ./Taskfile.sh build

    - name: Commit resources cache
      uses: EndBug/add-and-commit@v4
      with:
        message: "Deploy #${{ github.run_number }}"
        cwd: resources
        ref: resources
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove .git directory
      run: rm -rf public/.git

    - name: Install azcopy
      uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
    
    - name: Publish content
      run: ./Taskfile.sh deploy ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}