name: Check for regressions

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  regression-test:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'regression')
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        ref: master
    
    - name: Checkout resources cache
      uses: actions/checkout@v2
      with:
        ref: resources
        path: resources
    
    - name: Install dependencies
      run: |
        ./Taskfile.sh install

    - name: Generate Screenshots for reference
      run: |
        ./Taskfile.sh regression reference

    - name: Clean before checking out new code
      run: |
        git ls-files -z | xargs -r rm -f
        git ls-tree --name-only -d -r -z HEAD | sort -rz | xargs -0 rmdir 

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Checkout ${{ github.head_ref }}
      run: |
        git checkout origin/${{ github.head_ref }}

    - name: Install dependencies
      run: |
        ./Taskfile.sh install

    - name: Run regression test
      run: |
        ./Taskfile.sh regression test

    - name: Upload regression test results as an artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: regression-test-results
        path: backstop_data